name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_ci.yml"

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ vars.ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ vars.ACR_LOGIN_SERVER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Echo ACR vars
        run: |
          echo "ACR_NAME=$ACR_NAME"
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"

      - name: Login to Azure Container Registry
        run: az acr login -n "$ACR_NAME"

      - name: Build and Push Frontend Image
        run: |
          docker build -t "$ACR_LOGIN_SERVER/frontend:${{ github.sha }}" frontend
          docker push     "$ACR_LOGIN_SERVER/frontend:${{ github.sha }}"
          docker tag      "$ACR_LOGIN_SERVER/frontend:${{ github.sha }}" "$ACR_LOGIN_SERVER/frontend:latest"
          docker push     "$ACR_LOGIN_SERVER/frontend:latest"
